services:
  wordpress:
    build: .
    container_name: wordpress-sqlite
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ""
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'DISABLE_WP_CRON', true );
        define( 'WP_HTTP_BLOCK_EXTERNAL', true );
        define( 'DISALLOW_FILE_EDIT', true );
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./apache/performance.conf:/etc/apache2/conf-enabled/performance.conf:ro
      - ./apache/security.conf:/etc/apache2/conf-enabled/security.conf:ro
